# Generated by Django 4.2 on 2024-03-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=6, verbose_name='Código moeda entrada')),
                ('currency_code_in', models.CharField(max_length=6, verbose_name='Codigo moeda saida')),
                ('bid', models.DecimalField(decimal_places=5, default=0.0, max_digits=16, verbose_name='Compra')),
                ('ask', models.DecimalField(decimal_places=5, default=0.0, max_digits=16, verbose_name='Venda')),
                ('date_in', models.CharField(max_length=100, verbose_name='Data da cotação(em segundos)')),
                ('creation_datetime', models.DateTimeField(editable=False, verbose_name='Data de criação')),
                ('edition_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Taxa de câmbio',
                'verbose_name_plural': 'Taxas de câmbio',
                'db_table': 'excharge_rates',
                'ordering': ('-creation_datetime',),
            },
        ),
    ]
